### PR TITLE
Add org tags file export

### PR DESCRIPTION
**Pull request by tumashu**
Export org-brain to a org-mode file, include org tags, for example:

### CODE REVIEW

**Comment by tumashu** [comment]
For example:
```
#+TAGS: [ test1 :  test2 test3 ]
#+TAGS: [ test2 ]
#+TAGS: [ test3 ]
```

**Comment by Kungsgeten** [comment]
Hi! If I understand correctly, each line will contain an entry title, and the titles of this entry's children? What is the intended purpose of this? I think it might be confusing to name it "tags", since tags is something else in `org-mode`.

**Comment by tumashu** [comment]
yes, I use org-brain to manage org tags , so export to a tags file is a useful function

**Comment by Kungsgeten** [comment]
Wouldn't it be problematic if the title of entries include whitespace or other characters which aren't compatible with the `org` tag syntax?

**Comment by tumashu** [comment]
What about remove all chars which are not compatible with the org tag?

**Comment by Kungsgeten** [comment]
Yes, that seems like a good idea.

**Comment by tumashu** [comment]
Fixed, please review again.

**Comment by tumashu** [comment]
i have found a simpler way to deal with brain as tags, so this pr should close.

**Pull request closed without merging**
